### ISSUE TITLE
調整するファイルがわかりません

### ISSUE THREAD

**Issue by hohjukgi** [AutomotiveAIChallenge/aichallenge2022-sim#11]
初心者質問で恐縮なのですが

チュートリアルの順番通りにインストールを進めたところ
インストールが完了し、実際にコースを走行させることに成功しました

そこで質問なのですが

車の挙動などを調整したい場合、どこのファイルをどのように変更すればいいのでしょうか?

**Comment by naoto-mori-jq** [comment]
横から失礼します。

自分も同様の状態です。

Autoware universeの公式ドキュメントも難解で、苦戦しています。
簡単なAPIの使い方など教えて頂きたいです。
よろしくお願いします

**Comment by monaou** [comment]
横から失礼します。

自分も同様の状態です。

Autoware universeの公式ドキュメントも難解で、苦戦しています。
簡単なAPIの使い方など教えて頂きたいです。
よろしくお願いします

**Comment by Reee009876** [comment]
お世話になっております。

大変申し訳ございません。
このタイミングでのご説明は、競技の公平性の観点からいたしかねます。

ROS2コマンドやautowareの公式ドキュメント、README.mdなどを用いて，
ご対応のほど，よろしくお願いします．

ご要望にお応えできず誠に申し訳ございません。
