### ISSUE TITLE
dockerを更新してもサンプルの自動運転が開始しない（自己位置推定ができない）

### ISSUE THREAD

**Issue by seigot** [AutomotiveAIChallenge/aichallenge2022-sim#14]
表題の状況になっておりアドバイス頂けないでしょうか。

以下を参考にdockerを更新しました、しかしながら4.の部分で添付画像のような状況になり自己位置推定がうまくいっておりません。
4.の時点のrocker上のログを見るとERRORがいくつか出ているようですが、この辺りで何か想定されるエラー個所などわかりますでしょうか。すみませんがお願いいたします。
https://github.com/AutomotiveAIChallenge/aichallenge2022-sim/issues/6

4.RvizのタブにあるPanelからadd new Panelを開き、AutowareStatePanelを追加
5.自己位置推定ができていることを確認
6.正しく推定できていなければ、タブにある2D Pose Estimateを選択し、実際の車両の位置をドラッグで指定

![Screenshot from 2022-12-20 01-06-21](https://user-images.githubusercontent.com/46782860/208469351-afe2acc9-7741-41fb-aa9d-d2343c8c7626.png)

> [component_container-63] [WARN] [1671466577.943766958] [control.trajectory_follower.lane_departure_checker_node]: failed to get transform from map to base_link: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
[component_container-63] [INFO] [1671466577.943818324] [control.trajectory_follower.lane_departure_checker_node]: waiting for self pose...
[motion_velocity_smoother-57] [WARN] [1671466578.116429485] [planning.scenario_planning.motion_velocity_smoother]: failed to get transform from map to base_link: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
[motion_velocity_smoother-57] [INFO] [1671466578.116466589] [planning.scenario_planning.motion_velocity_smoother]: waiting for self pose...
[aggregator_node-20] [ERROR] [1671466578.133841860] [generic_analyzer_base]: Attempting to convert 255 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466578.133877884] [generic_analyzer_base]: Attempting to convert 224 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466578.133888595] [generic_analyzer_base]: Attempting to convert 52 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466578.133895267] [generic_analyzer_base]: Attempting to convert 111 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466578.133901907] [generic_analyzer_base]: Attempting to convert 64 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466579.133835107] [generic_analyzer_base]: Attempting to convert 255 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466579.133861886] [generic_analyzer_base]: Attempting to convert 224 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466579.133896271] [generic_analyzer_base]: Attempting to convert 52 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466579.133901542] [generic_analyzer_base]: Attempting to convert 111 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466579.133905712] [generic_analyzer_base]: Attempting to convert 64 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466580.133823810] [generic_analyzer_base]: Attempting to convert 255 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466580.133853436] [generic_analyzer_base]: Attempting to convert 224 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466580.133861150] [generic_analyzer_base]: Attempting to convert 52 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466580.133865520] [generic_analyzer_base]: Attempting to convert 111 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466580.133869832] [generic_analyzer_base]: Attempting to convert 64 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[component_container-61] [INFO] [1671466580.842849443] [planning.scenario_planning.parking.costmap_generator]: waiting for initial pose...
[aggregator_node-20] [ERROR] [1671466581.133865692] [generic_analyzer_base]: Attempting to convert 255 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466581.133898952] [generic_analyzer_base]: Attempting to convert 224 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466581.133907304] [generic_analyzer_base]: Attempting to convert 52 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466581.133911980] [generic_analyzer_base]: Attempting to convert 111 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466581.133916517] [generic_analyzer_base]: Attempting to convert 64 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[component_container_mt-60] [WARN] [1671466581.802123895] [planning.scenario_planning.lane_driving.motion_planning.obstacle_avoidance_planner]: failed to get transform from map to base_link: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
[component_container_mt-60] [INFO] [1671466581.802173966] [planning.scenario_planning.lane_driving.motion_planning.obstacle_avoidance_planner]: waiting for self pose...
[aggregator_node-20] [ERROR] [1671466582.133837585] [generic_analyzer_base]: Attempting to convert 255 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466582.133868636] [generic_analyzer_base]: Attempting to convert 224 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466582.133876974] [generic_analyzer_base]: Attempting to convert 52 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466582.133881582] [generic_analyzer_base]: Attempting to convert 111 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[aggregator_node-20] [ERROR] [1671466582.133885988] [generic_analyzer_base]: Attempting to convert 64 into DiagnosticLevel.
[aggregator_node-20]     Values are: {0: OK, 1: Warning, 2: Error, 3: Stale}
[component_container-63] [WARN] [1671466582.943909461] [control.trajectory_follower.lane_departure_checker_node]: failed to get transform from map to base_link: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
[component_container-63] [INFO] [1671466582.943947963] [control.trajectory_follower.lane_departure_checker_node]: waiting for self pose...
[motion_velocity_smoother-57] [WARN] [1671466583.116549456] [planning.scenario_planning.motion_velocity_smoother]: failed to get trans

**Comment by Reee009876** [comment]
お世話になっております。

ログを確認いたします。
その間に
コンテナ内で[ros2 topic list]を打っていただいてもよろしいでしょうか？

**Comment by seigot** [comment]
お世話になります！
rockerおよびros launchコマンド実行後、同じコンテナに別ターミナルから入って[ros2 topic list]を実行した結果は以下です
何か期待と異なる部分など、お気付きの点がありましたら共有頂けると助かりますm(_ _)m

> $ docker ps
CONTAINER ID   IMAGE          COMMAND       CREATED         STATUS         PORTS     NAMES
c525a1abd90c   553fbfe08217   "/bin/bash"   2 minutes ago   Up 2 minutes             elegant_solomon
$ docker exec -it elegant_solomon bash
$ ros2 topic list
/api/autoware/get/emergency
/api/autoware/get/engage
/api/autoware/get/map/info/hash
/api/autoware/get/observer
/api/autoware/get/operator
/api/autoware/get/route
/api/autoware/get/velocity_limit
/api/external/get/command/selected/control
/api/external/get/command/selected/vehicle
/api/external/get/cpu_usage
/api/external/get/diagnostics
/api/external/get/door
/api/external/get/emergency
/api/external/get/engage
/api/external/get/fail_safe/state
/api/external/get/map/info/hash
/api/external/get/observer
/api/external/get/operator
/api/external/get/route
/api/external/get/rtc_status
/api/external/get/service
/api/external/get/vehicle/status
/api/external/set/command/local/control
/api/external/set/command/local/heartbeat
/api/external/set/command/local/shift
/api/external/set/command/local/turn_signal
/api/external/set/command/remote/control
/api/external/set/command/remote/heartbeat
/api/external/set/command/remote/shift
/api/external/set/command/remote/turn_signal
/api/iv_msgs/autoware/state
/api/iv_msgs/perception/object_recognition/tracking/objects
/api/iv_msgs/planning/scenario_planning/trajectory
/api/iv_msgs/vehicle/status/control_mode
/api/localization/initialization_state
/api/motion/state
/api/routing/route
/api/routing/state
/autoware/engage
/autoware/state
/awapi/autoware/get/route
/awapi/autoware/get/stop_speed_exceeded
/awapi/prediction/get/objects
/awapi/tmp/virtual_traffic_light_states
/awapi/traffic_light/get/nearest_traffic_signal
/awapi/traffic_light/get/traffic_signals
/client_count
/clock
/connected_clients
/control/command/control_cmd
/control/current_gate_mode
/control/external_cmd_selector/current_selector_mode
/control/gate_mode_cmd
/control/trajectory_follower/control_cmd
/control/trajectory_follower/lane_departure_checker_node/debug/processing_time_ms
/control/trajectory_follower/lateral/diagnostic
/control/trajectory_follower/lateral/predicted_trajectory
/control/trajectory_follower/longitudinal/diagnostic
/control/trajectory_follower/longitudinal/slope_angle
/control/vehicle_cmd_gate/is_paused
/control/vehicle_cmd_gate/is_start_requested
/diagnostics
/diagnostics_agg
/diagnostics_err
/diagnostics_toplevel_state
/external/selected/control_cmd
/external/selected/external_control_cmd
/external/selected/gear_cmd
/external/selected/hazard_lights_cmd
/external/selected/heartbeat
/external/selected/turn_indicators_cmd
/external/traffic_light_recognition/traffic_signals
/initialpose
/initialpose3d
/joint_states
/localization/acceleration
/localization/debug/ellipse_marker
/localization/initialization_state
/localization/kinematic_state
/localization/pose_estimator/exe_time_ms
/localization/pose_estimator/initial_pose_with_covariance
/localization/pose_estimator/initial_to_result_distance
/localization/pose_estimator/initial_to_result_distance_new
/localization/pose_estimator/initial_to_result_distance_old
/localization/pose_estimator/iteration_num
/localization/pose_estimator/monte_carlo_initial_pose_marker
/localization/pose_estimator/ndt_marker
/localization/pose_estimator/nearest_voxel_transformation_likelihood
/localization/pose_estimator/points_aligned
/localization/pose_estimator/pose
/localization/pose_estimator/pose_with_covariance
/localization/pose_estimator/transform_probability
/localization/pose_twist_fusion_filter/biased_pose
/localization/pose_twist_fusion_filter/biased_pose_with_covariance
/localization/pose_twist_fusion_filter/debug
/localization/pose_twist_fusion_filter/debug/measured_pose
/localization/pose_twist_fusion_filter/debug/stop_flag
/localization/pose_twist_fusion_filter/estimated_yaw_bias
/localization/pose_twist_fusion_filter/kinematic_state
/localization/pose_twist_fusion_filter/pose
/localization/pose_twist_fusion_filter/twist
/localization/pose_twist_fusion_filter/twist_with_covariance
/localization/pose_with_covariance
/localization/twist_estimator/gyro_twist
/localization/twist_estimator/gyro_twist_raw
/localization/twist_estimator/twist_with_covariance
/localization/twist_estimator/twist_with_covariance_raw
/localization/util/crop_box_filter_measurement_range/crop_box_polygon
/localization/util/downsample/pointcloud
/localization/util/measurement_range/pointcloud
/localization/util/voxel_grid_downsample/pointcloud
/map/pointcloud_map
/map/vector_map
/map/vector_map_marker
/parameter_events
/perception/object_recognition/detection/centerpoint/objects
/perception/object_recognition/detection/centerpoint/validation/objects
/perception/object_recognition/detection/clustering/clusters
/perception/object_recognition/detection/clustering/debug/clusters
/perception/object_recognition/detection/clustering/downsampled/pointcloud
/perception/object_recognition/detection/clustering/objects
/perception/object_recognition/detection/clustering/objects_with_feature
/perception/object_recognition/detection/clustering/outlier_filter/pointcloud
/perception/object_recognition/detection/detection_by_tracker/debug/divided_objects
/perception/object_recognition/detection/detection_by_tracker/debug/initial_objects
/perception/object_recognition/detection/detection_by_tracker/debug/merged_objects
/perception/object_recognition/detection/detection_by_tracker/debug/tracked_objects
/perception/object_recognition/detection/detection_by_tracker/objects
/perception/object_recognition/detection/objects
/perception/object_recognition/detection/objects_before_filter
/perception/object_recognition/detection/pointcloud_map_filtered/pointcloud
/perception/object_recognition/detection/temporary_merged_objects
/perception/object_recognition/detection/voxel_based_compare_map_filter/debug/cyclic_time_ms
/perception/object_recognition/detection/voxel_based_compare_map_filter/debug/processing_time_ms
/perception/object_recognition/objects
/perception/object_recognition/prediction/maneuver
/perception/object_recognition/tracking/objects
/perception/obstacle_segmentation/crop_box_filter/crop_box_polygon
/perception/obstacle_segmentation/pointcloud
/perception/obstacle_segmentation/range_cropped/pointcloud
/perception/obstacle_segmentation/single_frame/pointcloud_raw
/perception/occupancy_grid_map/map
/perception/occupancy_grid_map/map_updates
/perception/traffic_light_recognition/debug/rois
/perception/traffic_light_recognition/rois
/perception/traffic_light_recognition/traffic_light_classifier/output/debug/image
/perception/traffic_light_recognition/traffic_light_classifier/output/debug/image/compressed
/perception/traffic_light_recognition/traffic_light_classifier/output/debug/image/compressedDepth
/perception/traffic_light_recognition/traffic_light_classifier/output/debug/image/theora
/perception/traffic_light_recognition/traffic_light_map_based_detector/debug/markers
/perception/traffic_light_recognition/traffic_signals
/perception/traffic_light_recognition/traffic_signals/markers
/planning/cooperate_status/avoidance_left
/planning/cooperate_status/avoidance_right
/planning/cooperate_status/blind_spot
/planning/cooperate_status/crosswalk
/planning/cooperate_status/detection_area
/planning/cooperate_status/intersection
/planning/cooperate_status/lane_change_left
/planning/cooperate_status/lane_change_right
/planning/cooperate_status/no_stopping_area
/planning/cooperate_status/occlusion_spot
/planning/cooperate_status/pull_out
/planning/cooperate_status/pull_over
/planning/cooperate_status/traffic_light
/planning/cooperate_status/virtual_traffic_light
/planning/hazard_lights_cmd
/planning/mission_planning/checkpoint
/planning/mission_planning/echo_back_goal_pose
/planning/mission_planning/goal
/planning/mission_planning/route
/planning/mission_planning/route_marker
/planning/mission_planning/route_state
/planning/planning_diagnostics/planning_error_monitor/debug/marker
/planning/scenario_planning/clear_velocity_limit
/planning/scenario_planning/current_max_velocity
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/avoidance
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/avoidance_debug_message_array
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/lanechange
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/lanefollowing
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/pullout
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/pullover
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/sideshift
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_boundary
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/input/lateral_offset
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/output/path_candidate
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/path_change_approval
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/blind_spot
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/crosswalk
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/detection_area
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/intersection
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/merge_from_private
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/no_stopping_area
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/occlusion_spot
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/path
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/stop_line
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/traffic_light
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/virtual_traffic_light
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/debug/walkway
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/input/external_crosswalk_states
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/input/external_intersection_states
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/output/stop_reason
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/blind_spot
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/crosswalk
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/detection_area
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/intersection
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/merge_from_private
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/no_stopping_area
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/occlusion_spot
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/run_out
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/stop_line
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/traffic_light
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/virtual_traffic_light
/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_wall/walkway
/planning/scenario_planning/lane_driving/behavior_planning/debug/traffic_signal
/planning/scenario_planning/lane_driving/behavior_planning/path
/planning/scenario_planning/lane_driving/behavior_planning/path_with_lane_id
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/area_with_objects
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/calculation_time
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/clearance_map
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/eb_trajectory
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/extended_fixed_traj
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/extended_non_fixed_traj
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/marker
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/mpt_fixed_traj
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/mpt_ref_traj
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/mpt_traj
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/object_clearance_map
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/virtual_wall
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/debug/wall_marker
/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/trajectory
/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/virtual_wall
/planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/virtual_wall
/planning/scenario_planning/lane_driving/obstacle_avoidance_approval
/planning/scenario_planning/lane_driving/trajectory
/planning/scenario_planning/max_velocity
/planning/scenario_planning/max_velocity_candidates
/planning/scenario_planning/max_velocity_default
/planning/scenario_planning/modified_goal
/planning/scenario_planning/motion_velocity_smoother/calculation_time
/planning/scenario_planning/motion_velocity_smoother/closest_acceleration
/planning/scenario_planning/motion_velocity_smoother/closest_jerk
/planning/scenario_planning/motion_velocity_smoother/closest_max_velocity
/planning/scenario_planning/motion_velocity_smoother/closest_merged_velocity
/planning/scenario_planning/motion_velocity_smoother/closest_velocity
/planning/scenario_planning/motion_velocity_smoother/debug/backward_filtered_trajectory
/planning/scenario_planning/motion_velocity_smoother/debug/forward_filtered_trajectory
/planning/scenario_planning/motion_velocity_smoother/debug/merged_filtered_trajectory
/planning/scenario_planning/motion_velocity_smoother/debug/trajectory_external_velocity_limited
/planning/scenario_planning/motion_velocity_smoother/debug/trajectory_lateral_acc_filtered
/planning/scenario_planning/motion_velocity_smoother/debug/trajectory_raw
/planning/scenario_planning/motion_velocity_smoother/debug/trajectory_steering_rate_limited
/planning/scenario_planning/motion_velocity_smoother/debug/trajectory_time_resampled
/planning/scenario_planning/motion_velocity_smoother/distance_to_stopline
/planning/scenario_planning/motion_velocity_smoother/stop_speed_exceeded
/planning/scenario_planning/parking/freespace_planner/debug/partial_pose_array
/planning/scenario_planning/parking/freespace_planner/debug/pose_array
/planning/scenario_planning/parking/is_completed
/planning/scenario_planning/parking/trajectory
/planning/scenario_planning/scenario
/planning/scenario_planning/scenario_selector/trajectory
/planning/scenario_planning/status/infrastructure_commands
/planning/scenario_planning/status/stop_reasons
/planning/scenario_planning/trajectory
/planning/steering_factor/avoidance
/planning/steering_factor/intersection
/planning/steering_factor/lane_change
/planning/steering_factor/pull_out
/planning/steering_factor/pull_over
/planning/turn_indicators_cmd
/robot_description
/rosout
/sensing/camera/traffic_light/camera_info
/sensing/camera/traffic_light/image_raw
/sensing/camera/traffic_light/image_raw/compressed
/sensing/gnss/pose_with_covariance
/sensing/imu/imu_data
/sensing/imu/tamagawa/imu_raw
/sensing/lidar/concatenated/pointcloud
/sensing/lidar/left/crop_box_filter_mirror/crop_box_polygon
/sensing/lidar/left/crop_box_filter_self/crop_box_polygon
/sensing/lidar/left/mirror_cropped/pointcloud_ex
/sensing/lidar/left/outlier_filtered/pointcloud
/sensing/lidar/left/pointcloud_raw_ex
/sensing/lidar/left/rectified/pointcloud_ex
/sensing/lidar/left/self_cropped/pointcloud_ex
/sensing/lidar/right/crop_box_filter_mirror/crop_box_polygon
/sensing/lidar/right/crop_box_filter_self/crop_box_polygon
/sensing/lidar/right/mirror_cropped/pointcloud_ex
/sensing/lidar/right/outlier_filtered/pointcloud
/sensing/lidar/right/pointcloud_raw_ex
/sensing/lidar/right/rectified/pointcloud_ex
/sensing/lidar/right/self_cropped/pointcloud_ex
/sensing/lidar/top/crop_box_filter_mirror/crop_box_polygon
/sensing/lidar/top/crop_box_filter_self/crop_box_polygon
/sensing/lidar/top/mirror_cropped/pointcloud_ex
/sensing/lidar/top/outlier_filtered/pointcloud
/sensing/lidar/top/pointcloud_raw_ex
/sensing/lidar/top/rectified/pointcloud_ex
/sensing/lidar/top/self_cropped/pointcloud_ex
/sensing/vehicle_velocity_converter/twist_with_covariance
/service_log
/simulation/dummy_perception_publisher/object_info
/system/component_state_monitor/component/autonomous/control
/system/component_state_monitor/component/autonomous/localization
/system/component_state_monitor/component/autonomous/map
/system/component_state_monitor/component/autonomous/perception
/system/component_state_monitor/component/autonomous/planning
/system/component_state_monitor/component/autonomous/sensing
/system/component_state_monitor/component/autonomous/system
/system/component_state_monitor/component/autonomous/vehicle
/system/component_state_monitor/component/launch/control
/system/component_state_monitor/component/launch/localization
/system/component_state_monitor/component/launch/map
/system/component_state_monitor/component/launch/perception
/system/component_state_monitor/component/launch/planning
/system/component_state_monitor/component/launch/sensing
/system/component_state_monitor/component/launch/system
/system/component_state_monitor/component/launch/vehicle
/system/emergency/control_cmd
/system/emergency/emergency_state
/system/emergency/gear_cmd
/system/emergency/hazard_lights_cmd
/system/emergency/hazard_status
/system/system_monitor/cpu_monitor/cpu_usage
/tf
/tf_static
/vehicle/engage
/vehicle/status/control_mode
/vehicle/status/door_status
/vehicle/status/gear_status
/vehicle/status/hazard_lights_status
/vehicle/status/steering_status
/vehicle/status/turn_indicators_status
/vehicle/status/velocity_status

**Comment by seigot** [comment]
ここでautowareが正しくmountできているかどうか確認します

> cd ./aichallenge2022-sim
rocker --nvidia --x11 --user --net host --privileged --volume autoware:/aichallenge -- ghcr.io/automotiveaichallenge/aichallenge2022-sim/autoware-universe-cuda:latest

**Comment by Reee009876** [comment]
以下を打っていただけますか？
`ros2 topic echo /sensing/lidar/top/pointcloud_raw`

**Comment by seigot** [comment]
遅くなりすみません、上記記載の状態でコメント頂いたコマンドを実行したところ以下のログが出力されました。
何かわかりましたらコメントいただけますと幸いです

```
ubuntu@ubuntu-FRONTIER:~$  ros2 topic echo /sensing/lidar/top/pointcloud_raw
WARNING: topic [/sensing/lidar/top/pointcloud_raw] does not appear to be published yet
Could not determine the type for the passed topic
```

**Comment by Reee009876** [comment]
ありがとうございます。

ホスト側とコンテナ側でトピック通信ができていないように見受けられます。
AWSIMを起動しておられるホスト側に、ROS2はインストールされていらっしゃいますか？
ご確認お願いします。

**Comment by seigot** [comment]
ご回答ありがとうございます、ホスト側へROS2をインストールができておりませんでした、、
解決しましたのでクローズさせて頂きます。初歩的な質問ですみません。
