### ISSUE TITLE
採点用のlaunchファイルについて

### ISSUE THREAD

**Issue by kosei1515** [AutomotiveAIChallenge/aichallenge2022-sim#23]
![image](https://user-images.githubusercontent.com/81236654/212456850-7b707698-44f2-4896-8572-ef68d22633cc.png)

提出する際にこのような画面が出ますが

全体を起動するlaunchファイルの名前は
aichallenge_submit.launch.xmlで間違いないでしょうか？

**Comment by Reee009876** [comment]
お世話になっております。

aichallenge.launch.xmlが大本のローンチとなっておりまして、そこから
評価用ノードとai_challenge_submit.launch.xmlが呼ばれるような処理となっております。

誤解を招く表現で、申し訳ありません。
明日、運営側で対応を相談いたします。

[各種パッケージについて](https://github.com/AutomotiveAIChallenge/aichallenge2022-sim#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
