### ISSUE TITLE
採点結果について

### ISSUE THREAD

**Issue by kosei1515** [AutomotiveAIChallenge/aichallenge2022-sim#25]
Advancedコースにおいて
採点完了となった状態で
タイムが0.00秒と表示されました

この場合はどのような状態でしょうか？

**Comment by kosei1515** [comment]
![image](https://user-images.githubusercontent.com/81236654/212461440-6f309f8e-3bfb-4627-8a7a-424659456c51.png)

**Comment by Reee009876** [comment]
お世話になっております。

明日、オンライン環境の確認を行います。
そのため、もうしばらくお待ちください。
