### ISSUE TITLE
2D Goal Pose を設定できないエラーについて

### ISSUE THREAD

**Issue by kazu1999** [AutomotiveAIChallenge/aichallenge2022-sim#27]
STATEがINITIALIZEから変化せず、2D Goal Poseを設定できない問題が起きております

こちらがコマンドの出力のテキストファイルを添付しておきました。
[log.txt](https://github.com/AutomotiveAIChallenge/aichallenge2022-sim/files/10422349/log.txt)

**Comment by Reee009876** [comment]
お世話になっております．

#20
と同じケースだと思われます．現在，調査中なため，もうしばらくお待ちください．

**Comment by Reee009876** [comment]
お時間を頂戴しており、大変申し訳ありません。

解決策が判明するまで、こちらの方法で対応いただけないでしょうか？
https://github.com/AutomotiveAIChallenge/aichallenge2022-sim/issues/20#issuecomment-1383122492

**Comment by kazu1999** [comment]
かしこまりました
