### ISSUE TITLE
採点スコアについて

### ISSUE THREAD

**Issue by kosei1515** [AutomotiveAIChallenge/aichallenge2022-sim#29]
簡単な質問で恐縮ですが
採点スコアはベストスコアではなく最新のものが採用される形でしょうか？

**Comment by Kenzo-Fujisaki** [comment]
https://github.com/AutomotiveAIChallenge/aichallenge2022-sim/blob/dd263d3057f658af1c387d96392fd7bc1006457c/README.md?plain=1#L292

最新のものが適応されるようです。
