### ISSUE TITLE
1日3回アップロードの件について

### ISSUE THREAD

**Issue by Kenzo-Fujisaki** [AutomotiveAIChallenge/aichallenge2022-sim#30]
一日3回アップロードできることになっていると思うのですが
これは、チームなのかアカウント単位なのかどちらでしょうか？

現在別のアカウントでアップロードしたところ
同じ名前のチーム名がランキングに表示されている状況です。

**Comment by dazzhe** [comment]
@Kenzo-Fujisaki 
大変申し訳ございません。現在サーバーの不具合でアカウント毎にアップロード制限、ランキング登録がされてしまっております。メールでもご連絡させていただきますが、以下ご確認お願いいたします。

---

現在サーバーの不具合で１つのチームで、複数の参加者がスコアを登録した際、同じチームのスコアが複数ランキングに登録されてしまう現象が発生しております。
チームの人数には1~3名の差があり、公平性のため1日に投稿できる回数は1チームあたり3回までとさせていただきたいため、誠に勝手ながら以下をお願いいたします。
・採点環境への提出は、１チーム毎に特定の１名に限ってください。
・もし、同じチームで複数のスコアを登録してしまった場合はどちらかを取り下げてください。

大会終了時に、同じチームで複数のスコアが登録されていた場合は、大会参加登録時のフォームに記入した順番で、若い番号の方による登録を採用して集計しますので、ご了承ください。

**Comment by Kenzo-Fujisaki** [comment]
ご返答いただきありがとうございます。片方を取り下げました。
お騒がせして申し訳ありませんでした。
