### ISSUE TITLE
Challengeコースのサンプルのエラーと対処法について

### ISSUE THREAD

**Issue by kosei1515** [AutomotiveAIChallenge/aichallenge2022-sim#6]
Challengeコースのサンプルのエラーと対処法を発見したので共有させていただきます

Error
- AWSIMを起動した後初期位置ははまっているがシミュレーションがスタートしない（毎回ではないが2回に1回くらい）
- 現在いる位置と同じような位置に初期位置をはめなおしても反応しない

Solution
- 一度少し違う位置に自己位置をはめなおすとスタートする　理由は謎

動作時の動画こちらになります

[Error.webm](https://user-images.githubusercontent.com/81236654/206631337-d9d367cb-bd93-4e4c-bf09-251a03fba6c3.webm)

可能であればエラーの解消をお願いしたいです．

**Comment by Reee009876** [comment]
お世話になっております。

情報のご共有ありがとうございます。
問題に関してですが、「シミュレータは動作するが、自動運転が開始されない」ということでよろしかったでしょうか？

上記であれば、「環境や負荷によっては自動運転が開始されないことがある」ことを
こちらでも確認しており、現在、原因・解決策を調査しているような状況です。
※チャレンジコース以外でも発生していることを確認しています。

大変申し訳ありません。
解決までは、記載頂いている方法で対処いただけると幸いです。

**Comment by kosei1515** [comment]
ご回答ありがとうございます

> シミュレータは動作するが、自動運転が開始されない

シミュレータが起動して画面に車とライダーのラインが映っている状態でシミュレータが動作しているのであればその認識で間違いないと思います

> ※チャレンジコース以外でも発生していることを確認しています。

参考までにですが
自分たちのPCではAdvancedコースで同様の現象は見受けられませんでした

お忙しい中恐縮ですがよろしくお願いします！

**Comment by Reee009876** [comment]
> シミュレータが起動して画面に車とライダーのラインが映っている状態でシミュレータが動作しているのであればその認識で間違いないと思います

こちらですが、[add new panel]からManualContollerを追加していただいて、手動操作をしての確認をお願いできないでしょうか？
![Screenshot from 2022-12-09 17-38-30](https://user-images.githubusercontent.com/113989589/206660313-8bca2698-3a91-4640-8b6a-7aec74d2ea13.png)

> 自分たちのPCではAdvancedコースで同様の現象は見受けられませんでした

追加情報ありがとうございます。

**Comment by kosei1515** [comment]
やってみました　こちら動画です
おそらくシミュレータは動作していると思います

[Screencast from 12-09-2022 07:02:02 PM.webm](https://user-images.githubusercontent.com/81236654/206676996-f2dee84f-a3bc-46a9-8845-99cc0f8f1d56.webm)

**Comment by Reee009876** [comment]
お世話になっております。

自己位置がうまくいかない問題に対応した
docker imageを公開しました。
一度、こちらをお試しいただけないでしょうか？

https://github.com/AutomotiveAIChallenge/aichallenge2022-sim/issues/1

**Comment by Reee009876** [comment]
こちら、修正版のアップロードが完了しておりますため、
クローズとさせていただきます。

また、疑問などがございましたら
再オープンをお願いします。
