### ISSUE TITLE
AIチャレンジに参加可能なPCの最低スペックは？

### ISSUE THREAD

**Issue by hir-yk** [AutomotiveAIChallenge/aichallenge2022-sim#7]
もともとの推奨スペックが高すぎて参加障壁が高そうなので、手元にある低スペック(???)なノートPCで試してみました。AWSIM + Autoware を起動して challenge コースを、動きカクカクながらも走破できました

```
CPU:Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz （4コア8スレッド）
GPU:GeForce GTX 1080 Mobile
RAM:32G
```

issueでもなんでもないので即closeで良いかもです。とりあえずあげてみます

**Comment by Reee009876** [comment]
低スペックPCの場合、AWSIM内の時間の流れを遅くすれば、落ちたりせずに動作するかもしれません。
お試しいただければと思います。

上記を利用する場合や不安定な環境を使用したじょで作成・動作させたプログラムをオンライン環境にアップした際の動作に関しましては、
参加者様の想像どおりに動く保証はないため、その点だけご留意いただければ幸いです。

**Comment by Reee009876** [comment]
低スペックPCの場合、AWSIM内の時間の流れを遅くすれば、落ちたりせずに動作するかもしれません。

しかし、上記の方法や低スペックなPCなどの不安定な環境を利用して作成・動作確認されたプログラムを
オンライン環境にアップした際の動作に関しましては、参加者様の想定どおりに動くという保証ができません。
その点だけご留意いただければ幸いです。

**Comment by anpanium** [comment]
最低限の性能を満たすPCを持っておらずクラウドサーバーを借りようと思っているのですがデータ転送量はどれくらいで概算すればよいでしょうか？

**Comment by hir-yk** [comment]
長いこと放置してしまいました。close
