### ISSUE TITLE
自車両がひっかかります

### ISSUE THREAD

**Issue by hir-yk** [AutomotiveAIChallenge/aichallenge2022-sim#9]
交差点を曲がるときに自車両が引っかかり急減速します。原因わかりますでしょうか？

https://user-images.githubusercontent.com/84175137/207533304-c8fa2ad5-13ce-4335-9590-9a66f56d5a76.mp4

**Comment by Reee009876** [comment]
お世話になっております。
ご連絡が遅くなり、大変申し訳ありません。

現在、対応を検討中です。
もうしばらくお待ちください。

**Comment by Reee009876** [comment]
こちらでのご案内が漏れており、大変申し訳ありません。
READMEにて、修正版のアップロードが完了しておりますため、クローズとさせていただきます。

また、疑問などがございましたら
再オープンをお願いします。
